### ISSUE TITLE
v6: memory races

### ISSUE THREAD

**Issue by rogpeppe** [configcat/go-sdk#14]
Running the tests with `go test -race` shows some places where there seem to be memory races in the code.
For example, `lazyLoadingPolicy.fetch` sets `policy.lastRefreshTime` asynchronously [without any kind of
memory guard](https://github.com/configcat/go-sdk/blob/master/v6/lazy_loading_policy.go#L107).

The whole async-callback approach used in the package is non-idiomatic for Go and might be worth  revisiting.

**Comment by z4kn4fein** [comment]
Thanks for opening this issue!
I created a ticket on our backlog to resolve it. Besides, I would be more than happy to receive suggestions about improving this SDK to be more idiomatic. Feel free to reach me out directly in our [community slack](https://join.slack.com/t/configcat-community/shared_invite/enQtMzkwNDg3MjQ3MTUyLWY1ZmE0NjY5NjA0YjAzMWU3MDg3ODhkMGI2ZjdmZjZmYTY4YTg1NmQ0YzBhMTVhOGE5YmNiYTI5OTg4NmNjYTQ).

Thanks for your work in reviewing this SDK, this helps a lot to make it more valuable!

**Comment by z4kn4fein** [comment]
The refactor which fixed this was released in [v6.1.0](https://github.com/configcat/go-sdk/releases/tag/v6.1.0)
