### ISSUE TITLE
Default logging is too verbose

### ISSUE THREAD

**Issue by ryanskidmore** [configcat/go-sdk#4]
Would it be possible to have verbose logging as an optional configurable? The overly verbose logging is too loud for normal use - I don't care about every single feature flag evaluation but may be a feature that's useful when debugging an issue.

**Comment by configcat** [comment]
Hi Ryan! Thanks for the feedback. Here is how you can set log level: https://configcat.com/docs/sdk-reference/go/#logging Do you have any better idea how to do this?

**Comment by ryanskidmore** [comment]
Thanks for getting back to me so quickly @configcat! My suggestion would be to have a log level param in the `ClientConfig` struct which is used to initialise the `logrus` instance. This would be cleaner than creating a new `logrus` instance, setting in the log level and passing that into the `ClientConfig` struct. 

Happy to do a PR for this if you think this approach would be better?

**Comment by sigewuzhere** [comment]
@ryanskidmore 
I totally agree, having a log level param is way cleaner.
A PR would be awesome.
Thanks in advance! :)

**Comment by ryanskidmore** [comment]
@configcat @sigewuzhere PR here: #7

**Comment by configcat** [comment]
Released in [v4.0.4](https://github.com/configcat/go-sdk/releases/tag/v4.0.4)
