### ISSUE TITLE
Open Feature provider

### ISSUE THREAD

**Issue by rcrowe** [configcat/go-sdk#60]
### Is your feature request related to a problem? Please describe.

[We](http://github.com/utilitywarehouse) are migrating to Open Feature across our clients & want a ConfigCat provider.

### Describe the solution you'd like

An OSS provider that is either part of the [official repo](https://github.com/open-feature/go-sdk-contrib/tree/main/providers), natively in this SDK or a defacto community implementation that is linked to.

### Describe alternatives you've considered

Implementing the provider ourselves, which depending on the response here we're going to start looking at shortly.

**Comment by laliconfigcat** [comment]
Hello @rcrowe,

Thanks for reaching out. Providing an official OpenFeature client is on our roadmap but we don't expect to start the development this year. It would be awesome if you could implement the provider. We can help reviewing it and answering any questions that come up during the development.
Let me know if this works for you. If yes, I'd suggest you to join our community slack channel (https://configcat.com/slack/) where we can create a dedicated channel and discuss this topic further.

Cheers,
Lali

**Comment by rcrowe** [comment]
Completed by https://github.com/open-feature/go-sdk-contrib/pull/242

Released:
https://github.com/open-feature/go-sdk-contrib/releases/tag/providers%2Fconfigcat%2Fv0.1.1
