### ISSUE TITLE
Enable config for map type. 

### ISSUE THREAD

**Issue by jennwah** [configcat/go-sdk#62]
### Is your feature request related to a problem? Please describe.

Having a map data structure type as config would be good for many reasons. Right now we can still use existing `string` data type, but it is capped by the max 1000 characters which is annoying.

### Additional context

Add any other context about the feature request here.

**Comment by z4kn4fein** [comment]
Hi @jennwah, thanks for reaching out! 

Could you please explain a bit more about what you mean by `config`? Is it a `string` feature flag's value? Also, where do you experience the 1000 char limit exactly?
